data:
  block_size: 512
  cnhubertsoft_gate: 10
  duration: 2
  encoder: hubertsoft
  encoder_hop_size: 320
  encoder_out_channels: 256
  encoder_sample_rate: 16000
  extensions:
  - wav
  sampling_rate: 44100
  training_files: filelists/train.txt
  unit_interpolate_mode: nearest
  validation_files: filelists/val.txt
device: cuda
env:
  expdir: logs/44k/diffusion
  gpu_id: 0
infer:
  method: dpm-solver
  speedup: 10
model:
  n_chans: 512
  n_hidden: 256
  n_layers: 20
  n_spk: 1
  type: Diffusion
  use_pitch_aug: true
spk:
  CHENLIN2.0: 0
train:
  amp_dtype: fp16
  batch_size: 75
  cache_all_data: true
  cache_device: cuda
  cache_fp16: true
  decay_step: 100000
  epochs: 100000
  gamma: 0.5
  interval_force_save: 2000
  interval_log: 10
  interval_val: 2000
  lr: 0.0002
  num_workers: 0
  save_opt: false
  weight_decay: 0
vocoder:
  ckpt: pretrain/nsf_hifigan/model
  type: nsf-hifigan
